### ISSUE TITLE
Deprecated find_element_by_* and find_elements_by_* are now removed?

### ISSUE THREAD

**Issue by andyberg1** [pablobiedma/TicketSwapMe#5] opened 2023-06-22 08:48 UTC
Hi, is this still working? Need some help.

**Comment by pablobiedma** [comment] 2023-06-22 09:56
Thank you for showing interest in the repository. 
I haven't run this project in a while, but unless Ticketswap has modified its source code and paths, everything should work. 
Could you please create an issue with the specific question that you have? 
Good luck finding a ticket 😄

**Comment by andyberg1** [comment] 2023-06-22 09:59
Hi, I think it's a problem on my side with running it on the right way. Can you help me set it  up?

**Comment by pablobiedma** [comment] 2023-06-22 10:21
Feel free to indicate the issues you are facing and I will try my best to assist you further

**Comment by andyberg1** [comment] 2023-06-22 10:24
I saw this: Selenium 4.3.0
* Deprecated find_element_by_* and find_elements_by_* are now removed (#10712)

So I think some of the script have te be renewed? Because It gives me an error with selenium.

**Comment by andyberg1** [comment] 2023-06-22 10:34
thanks, and what are the elements I need to fill?
Email
Password
ticket link?

**Comment by pablobiedma** [comment] 2023-06-22 11:03
Yes, I managed to replace the deprecated selenium code. Take a look at my pull request and try to use that code. I will probably need to replace some of the XPATHs. Working on it right now

**Comment by pablobiedma** [comment] 2023-06-22 11:15
Yes, I managed to fix the deprecated Selenium code. The XPATHS seems to be updated as well. I updated the login. Can you take care of the remaining ones? (eg. lines 62-76). Once you do this everything should be fine,  please submit a pull request with the changes.

**Comment by andyberg1** [comment] 2023-06-22 11:27
Hi, got this problem now, after running the new code 
![image](https://github.com/pablobiedma/TicketSwapMe/assets/64000831/04da9012-ac86-4c57-94cf-d97761f943e6)

**Comment by pablobiedma** [comment] 2023-06-22 11:53
That is strange because the path works for me. But click on the element, inspect, copy XPATH, and then try by yourself.

**Comment by andyberg1** [comment] 2023-06-22 11:55
fixed that problem, but roll into the next one: what do I need to put here?

            letter = self.driver.find_element(By.CSS_SELECTOR, 'div.css-1nxi1g2:nth-child(1) > h2:nth-child(1)').text
            if int(letter) > 0:
                print(str(letter) + " are available")
                try:
                    self.driver.find_element(By.CSS_SELECTOR, 'div.css-uirvwh:nth-child(2) > ul:nth-child(1) > div:nth-child(1) > a:nth-child(1) > div:nth-child(1)').click()
                    time.sleep(3)
                    self.driver.find_element(By.CSS_SELECTOR, '.css-1aros5x').click()
                except NoSuchElementException:
                    print("")
                try:
                    self.driver.find_element(By.XPATH, '/html/body/div/div[3]/div[3]/div/a[1]/div').click()
                    time.sleep(3)
                    self.driver.find_element(By.CSS_SELECTOR, 'div.css-uirvwh:nth-child(2) > ul:nth-child(1) > div:nth-child(1) > a:nth-child(1) > div:nth-child(1)').click()
                    time.sleep(3)
                    self.driver.find_element(By.CSS_SELECTOR, '.css-1aros5x').click()
                except _**NoSuchElementException:**_
                    print("")

**Comment by pablobiedma** [comment] 2023-06-22 12:52
I wrote this code 4 years ago so I do not entirely remember and cannot check one by one right now, unfortunately.
But if you manage to find out and replace the outdated paths, please do let me know!

**Comment by blueboxboz** [comment] 2023-07-19 10:43
got it working again :)?

**Comment by pablobiedma** [comment] 2023-07-19 10:48
ask @andyberg1, also If you are encountering an alternative error please feel free to post it in a separate issue

**Comment by blueboxboz** [comment] 2023-07-19 10:49
too bad! was hoping to go to Coldplay tonight :) thanks for your response!

**Comment by pablobiedma** [comment] 2023-07-19 11:06
I feel you... I would suggest to ask bard.google.com to update the depracated xpaths of the code using the ticketswap.nl website. Maybe it will work

**Comment by blueboxboz** [comment] 2023-07-19 13:59
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException

import json
import time
import requests
import tkinter as tk
from tkinter import simpledialog
import webbrowser

from selenium.webdriver.firefox.options import Options

try:
    from BeautifulSoup import BeautifulSoup
except ImportError:
    from bs4 import BeautifulSoup

HOST = "https://www.ticketswap.nl"

class TicketSwapMe:
    def __init__(self):
        self.driver = webdriver.Firefox()
        self.login()
        self.has_tickets = False

    def login(self):
        username = 
        password = 

        self.driver.get(HOST)
        login_button = self.driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/nav/div[1]/ul/li[3]/button")
        login_button.click()
        time.sleep(3)
        facebook_button = self.driver.find_elements(By.XPATH, "//*[contains(text(), 'Doorgaan met Facebook')]")[1]
        facebook_button.click()
        time.sleep(2)
        self.driver.switch_to.window(self.driver.window_handles[1])
        time.sleep(4)
        user_input = self.driver.find_element(By.ID, 'email')
        pass_input = self.driver.find_element(By.ID, 'pass')

        user_input.send_keys(username)
        pass_input.send_keys(password)
        pass_input.send_keys(Keys.RETURN)
        self.driver.switch_to.window(self.driver.window_handles[0])

        self.cookies = self.__handle_cookies(self.driver.get_cookies())

    def __handle_cookies(self, cookie_list):
        cookies = {}
        for cookie in cookie_list:
            cookies[cookie['name']] = cookie['value']
        return cookies

    def start(self):
        time.sleep(7)
        self.driver.get('https://www.ticketswap.com/event/coldplay-music-of-the-spheres-world-tour/seats-tickets/b44f2882-04e2-496c-abea-7c460615209e/2396863')

        while True:
            try:
                letter = self.driver.find_element(By.CLASS_NAME, 'seat-availability')
            except NoSuchElementException:
                print("No tickets are available. Keep trying")
                continue           
            
            if letter is not None and letter.is_displayed():
                print(str(letter) + " are available")
                try:
                    self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div/a[1]/div/div[1]').click()
                    time.sleep(3)
                    self.driver.find_element(By.XPATH, '.css-1aros5x').click()
                except NoSuchElementException:
                    print("")
                try:
                    if not self.driver.find_element(By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div/a[1]/div').is_displayed():
                        for i in range(100):
                            self.driver.execute_script('window.scrollBy(0, 100);', 50)
                            letter = self.driver.find_element(By.CLASS_NAME, 'seat-availability')
                            if letter is not None and letter.is_displayed():
                                break
                    letter = self.driver.find_element(By.CLASS_NAME, 'seat-availability')
                except NoSuchElementException:
                    print("")

                break
            else:
                print("No tickets are available. Keep trying")
            self.driver.refresh()

    def get_ticket(self, event_url):
        """ Get Cheapest ticket """
        self.driver.get(event_url)

    def explode_ticket(self, ticket_link):
        """ Gets tokens from ticket page """
        response = requests.get(HOST + ticket_link, cookies=self.cookies)
        parsed_html = BeautifulSoup(response.content.decode("utf-8"), "html.parser")
        token_object = parsed_html.body.find('input', attrs={"name": "reserve[_token]"})
        if token_object is None:
            print("Failed to get token")
            return False
        token_attrs = token_object.attrs
        reserve_token_object = parsed_html.body.find('input', attrs={"name": "reserve[_token]"})

        if reserve_token_object is None:
            return False
        reserve_token_attrs = reserve_token_object.attrs
        add_data = {}
        seats = parsed_html.body.find('input', attrs={'name': 'tickets[]'})
        if seats is not None:
            add_data['tickets[]'] = seats.attrs['value']
        else:
            items = parsed_html.body.find('select', attrs={'name': 'amount'})
            count = len(items.findChildren())
            add_data['amount'] = count
        token = token_attrs['value']
        reserve_token = reserve_token_attrs['value']
        ticket_link_reserve = parsed_html.body.find('form', attrs={"id": "listing-reserve-form"}).attrs
        ticket_reserve_link = ticket_link_reserve['data-endpoint']
        return {"token": token,
                "reserve_token": reserve_token,
                "ticket_link": ticket_reserve_link,
                "more_data": add_data}

    def reserve_ticket(self, content):
        """ Reserve ticket """
        token = content['token']
        reserve_token = content['reserve_token']
        form_data = {"token": token, "reserve[_token]": reserve_token, **content['more_data']}
        ticket = requests.post(HOST + content['ticket_link'], data=form_data, cookies=self.cookies)
        content = json.loads(ticket.content.decode("utf-8"))
        print('Successfully added ticket to your account')
        return bool(content['success'])

if __name__ == "__main__":
    ROOT = tk.Tk()
    ROOT.withdraw()
    t = TicketSwapMe()
    t.start()



i keep getting no tickets are available, you think the code should work fine ?

**Comment by pablobiedma** [comment] 2023-07-20 12:02
That appears to be expected behavior. You can also try a concert with available tickets to see if it works fine in that situation.

**Comment by pablobiedma** [comment] 2023-07-20 12:08
@blueboxboz For now, I will close this issue. If you get this code to work, feel free to do a pull request with it so that we can add the updated version to the repository.

**Closed by pablobiedma** 2023-07-20 12:08 UTC

**Comment by BruteS7** [comment] 2023-10-10 17:25
@blueboxboz have you got it running? Would love to get some tickets for some shows...thanks in advance

**Comment by BruteS7** [comment] 2023-10-10 17:26
@andyberg1 did it work for you? thanks in advance
